networks:
  local_docker:
    external: true

services:
  mariadb:
    platform: ${PLATFORM:-linux/x86_64}
    # platform: linux/arm64/v8
    image: mariadb:10.6
    container_name: mariadb-container
    restart: on-failure:5
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql # Persistent data storage
      - ./mariadb/config:/etc/mysql/conf.d # Custom configuration directory
      - ./mariadb/logs:/var/log/mysql # Separate log storage
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4', # Set UTF-8 encoding
        '--collation-server=utf8mb4_unicode_ci', # Set collation for Unicode compatibility
        '--log-error=/var/lib/mysql/mariadb-error.log' # Set the location for error logs
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    networks:
      - local_docker

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ABSOLUTE_TIMEOUT: 28800 # Sets phpMyAdmin session timeout to 8 hours
    depends_on:
      - mariadb
    networks:
      - local_docker